// Generated by gencpp from file wam_common/BHandSpreadVel.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_BHANDSPREADVEL_H
#define WAM_COMMON_MESSAGE_BHANDSPREADVEL_H

#include <ros/service_traits.h>


#include <wam_common/BHandSpreadVelRequest.h>
#include <wam_common/BHandSpreadVelResponse.h>


namespace wam_common
{

struct BHandSpreadVel
{

typedef BHandSpreadVelRequest Request;
typedef BHandSpreadVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandSpreadVel
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::BHandSpreadVel > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::wam_common::BHandSpreadVel&) { return value(); }
};

template<>
struct DataType< ::wam_common::BHandSpreadVel > {
  static const char* value()
  {
    return "wam_common/BHandSpreadVel";
  }

  static const char* value(const ::wam_common::BHandSpreadVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::BHandSpreadVelRequest> should match
// service_traits::MD5Sum< ::wam_common::BHandSpreadVel >
template<>
struct MD5Sum< ::wam_common::BHandSpreadVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_common::BHandSpreadVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandSpreadVelRequest> should match
// service_traits::DataType< ::wam_common::BHandSpreadVel >
template<>
struct DataType< ::wam_common::BHandSpreadVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_common::BHandSpreadVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::BHandSpreadVelResponse> should match
// service_traits::MD5Sum< ::wam_common::BHandSpreadVel >
template<>
struct MD5Sum< ::wam_common::BHandSpreadVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_common::BHandSpreadVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandSpreadVelResponse> should match
// service_traits::DataType< ::wam_common::BHandSpreadVel >
template<>
struct DataType< ::wam_common::BHandSpreadVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_common::BHandSpreadVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_BHANDSPREADVEL_H
