// Generated by gencpp from file wam_common/BHandGraspPos.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_BHANDGRASPPOS_H
#define WAM_COMMON_MESSAGE_BHANDGRASPPOS_H

#include <ros/service_traits.h>


#include <wam_common/BHandGraspPosRequest.h>
#include <wam_common/BHandGraspPosResponse.h>


namespace wam_common
{

struct BHandGraspPos
{

typedef BHandGraspPosRequest Request;
typedef BHandGraspPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandGraspPos
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::BHandGraspPos > {
  static const char* value()
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const ::wam_common::BHandGraspPos&) { return value(); }
};

template<>
struct DataType< ::wam_common::BHandGraspPos > {
  static const char* value()
  {
    return "wam_common/BHandGraspPos";
  }

  static const char* value(const ::wam_common::BHandGraspPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::BHandGraspPosRequest> should match
// service_traits::MD5Sum< ::wam_common::BHandGraspPos >
template<>
struct MD5Sum< ::wam_common::BHandGraspPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_common::BHandGraspPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandGraspPosRequest> should match
// service_traits::DataType< ::wam_common::BHandGraspPos >
template<>
struct DataType< ::wam_common::BHandGraspPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_common::BHandGraspPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::BHandGraspPosResponse> should match
// service_traits::MD5Sum< ::wam_common::BHandGraspPos >
template<>
struct MD5Sum< ::wam_common::BHandGraspPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_common::BHandGraspPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandGraspPosResponse> should match
// service_traits::DataType< ::wam_common::BHandGraspPos >
template<>
struct DataType< ::wam_common::BHandGraspPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandGraspPos >::value();
  }
  static const char* value(const ::wam_common::BHandGraspPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_BHANDGRASPPOS_H
