// Generated by gencpp from file wam_common/CouplingWam.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_COUPLINGWAM_H
#define WAM_COMMON_MESSAGE_COUPLINGWAM_H

#include <ros/service_traits.h>


#include <wam_common/CouplingWamRequest.h>
#include <wam_common/CouplingWamResponse.h>


namespace wam_common
{

struct CouplingWam
{

typedef CouplingWamRequest Request;
typedef CouplingWamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CouplingWam
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::CouplingWam > {
  static const char* value()
  {
    return "673873b0d5bf0a07d3f41369f70ccd47";
  }

  static const char* value(const ::wam_common::CouplingWam&) { return value(); }
};

template<>
struct DataType< ::wam_common::CouplingWam > {
  static const char* value()
  {
    return "wam_common/CouplingWam";
  }

  static const char* value(const ::wam_common::CouplingWam&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::CouplingWamRequest> should match
// service_traits::MD5Sum< ::wam_common::CouplingWam >
template<>
struct MD5Sum< ::wam_common::CouplingWamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::CouplingWam >::value();
  }
  static const char* value(const ::wam_common::CouplingWamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::CouplingWamRequest> should match
// service_traits::DataType< ::wam_common::CouplingWam >
template<>
struct DataType< ::wam_common::CouplingWamRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::CouplingWam >::value();
  }
  static const char* value(const ::wam_common::CouplingWamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::CouplingWamResponse> should match
// service_traits::MD5Sum< ::wam_common::CouplingWam >
template<>
struct MD5Sum< ::wam_common::CouplingWamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::CouplingWam >::value();
  }
  static const char* value(const ::wam_common::CouplingWamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::CouplingWamResponse> should match
// service_traits::DataType< ::wam_common::CouplingWam >
template<>
struct DataType< ::wam_common::CouplingWamResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::CouplingWam >::value();
  }
  static const char* value(const ::wam_common::CouplingWamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_COUPLINGWAM_H
