// Generated by gencpp from file wam_common/IdleWam.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_IDLEWAM_H
#define WAM_COMMON_MESSAGE_IDLEWAM_H

#include <ros/service_traits.h>


#include <wam_common/IdleWamRequest.h>
#include <wam_common/IdleWamResponse.h>


namespace wam_common
{

struct IdleWam
{

typedef IdleWamRequest Request;
typedef IdleWamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IdleWam
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::IdleWam > {
  static const char* value()
  {
    return "b5b49ecafd180af8ba5b1be89bbf053c";
  }

  static const char* value(const ::wam_common::IdleWam&) { return value(); }
};

template<>
struct DataType< ::wam_common::IdleWam > {
  static const char* value()
  {
    return "wam_common/IdleWam";
  }

  static const char* value(const ::wam_common::IdleWam&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::IdleWamRequest> should match
// service_traits::MD5Sum< ::wam_common::IdleWam >
template<>
struct MD5Sum< ::wam_common::IdleWamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::IdleWam >::value();
  }
  static const char* value(const ::wam_common::IdleWamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::IdleWamRequest> should match
// service_traits::DataType< ::wam_common::IdleWam >
template<>
struct DataType< ::wam_common::IdleWamRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::IdleWam >::value();
  }
  static const char* value(const ::wam_common::IdleWamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::IdleWamResponse> should match
// service_traits::MD5Sum< ::wam_common::IdleWam >
template<>
struct MD5Sum< ::wam_common::IdleWamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::IdleWam >::value();
  }
  static const char* value(const ::wam_common::IdleWamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::IdleWamResponse> should match
// service_traits::DataType< ::wam_common::IdleWam >
template<>
struct DataType< ::wam_common::IdleWamResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::IdleWam >::value();
  }
  static const char* value(const ::wam_common::IdleWamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_IDLEWAM_H
