// Generated by gencpp from file wam_common/JointMove.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_JOINTMOVE_H
#define WAM_COMMON_MESSAGE_JOINTMOVE_H

#include <ros/service_traits.h>


#include <wam_common/JointMoveRequest.h>
#include <wam_common/JointMoveResponse.h>


namespace wam_common
{

struct JointMove
{

typedef JointMoveRequest Request;
typedef JointMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMove
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::JointMove > {
  static const char* value()
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const ::wam_common::JointMove&) { return value(); }
};

template<>
struct DataType< ::wam_common::JointMove > {
  static const char* value()
  {
    return "wam_common/JointMove";
  }

  static const char* value(const ::wam_common::JointMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::JointMoveRequest> should match
// service_traits::MD5Sum< ::wam_common::JointMove >
template<>
struct MD5Sum< ::wam_common::JointMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::JointMove >::value();
  }
  static const char* value(const ::wam_common::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::JointMoveRequest> should match
// service_traits::DataType< ::wam_common::JointMove >
template<>
struct DataType< ::wam_common::JointMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::JointMove >::value();
  }
  static const char* value(const ::wam_common::JointMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::JointMoveResponse> should match
// service_traits::MD5Sum< ::wam_common::JointMove >
template<>
struct MD5Sum< ::wam_common::JointMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::JointMove >::value();
  }
  static const char* value(const ::wam_common::JointMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::JointMoveResponse> should match
// service_traits::DataType< ::wam_common::JointMove >
template<>
struct DataType< ::wam_common::JointMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::JointMove >::value();
  }
  static const char* value(const ::wam_common::JointMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_JOINTMOVE_H
