// Generated by gencpp from file wam_common/RTJointVel.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_RTJOINTVEL_H
#define WAM_COMMON_MESSAGE_RTJOINTVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct RTJointVel_
{
  typedef RTJointVel_<ContainerAllocator> Type;

  RTJointVel_()
    : velocities()  {
    }
  RTJointVel_(const ContainerAllocator& _alloc)
    : velocities(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _velocities_type;
  _velocities_type velocities;





  typedef boost::shared_ptr< ::wam_common::RTJointVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::RTJointVel_<ContainerAllocator> const> ConstPtr;

}; // struct RTJointVel_

typedef ::wam_common::RTJointVel_<std::allocator<void> > RTJointVel;

typedef boost::shared_ptr< ::wam_common::RTJointVel > RTJointVelPtr;
typedef boost::shared_ptr< ::wam_common::RTJointVel const> RTJointVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::RTJointVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::RTJointVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::RTJointVel_<ContainerAllocator1> & lhs, const ::wam_common::RTJointVel_<ContainerAllocator2> & rhs)
{
  return lhs.velocities == rhs.velocities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::RTJointVel_<ContainerAllocator1> & lhs, const ::wam_common::RTJointVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::RTJointVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::RTJointVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::RTJointVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::RTJointVel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::RTJointVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::RTJointVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::RTJointVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b1dee67c9ae4d5adf87be09d4bf02ef";
  }

  static const char* value(const ::wam_common::RTJointVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b1dee67c9ae4d5aULL;
  static const uint64_t static_value2 = 0xdf87be09d4bf02efULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::RTJointVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/RTJointVel";
  }

  static const char* value(const ::wam_common::RTJointVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::RTJointVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] velocities\n"
;
  }

  static const char* value(const ::wam_common::RTJointVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::RTJointVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTJointVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::RTJointVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::RTJointVel_<ContainerAllocator>& v)
  {
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_RTJOINTVEL_H
