// Generated by gencpp from file wam_common/BHandGraspVel.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_BHANDGRASPVEL_H
#define WAM_COMMON_MESSAGE_BHANDGRASPVEL_H

#include <ros/service_traits.h>


#include <wam_common/BHandGraspVelRequest.h>
#include <wam_common/BHandGraspVelResponse.h>


namespace wam_common
{

struct BHandGraspVel
{

typedef BHandGraspVelRequest Request;
typedef BHandGraspVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandGraspVel
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::BHandGraspVel > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::wam_common::BHandGraspVel&) { return value(); }
};

template<>
struct DataType< ::wam_common::BHandGraspVel > {
  static const char* value()
  {
    return "wam_common/BHandGraspVel";
  }

  static const char* value(const ::wam_common::BHandGraspVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::BHandGraspVelRequest> should match
// service_traits::MD5Sum< ::wam_common::BHandGraspVel >
template<>
struct MD5Sum< ::wam_common::BHandGraspVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_common::BHandGraspVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandGraspVelRequest> should match
// service_traits::DataType< ::wam_common::BHandGraspVel >
template<>
struct DataType< ::wam_common::BHandGraspVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_common::BHandGraspVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::BHandGraspVelResponse> should match
// service_traits::MD5Sum< ::wam_common::BHandGraspVel >
template<>
struct MD5Sum< ::wam_common::BHandGraspVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_common::BHandGraspVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandGraspVelResponse> should match
// service_traits::DataType< ::wam_common::BHandGraspVel >
template<>
struct DataType< ::wam_common::BHandGraspVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_common::BHandGraspVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_BHANDGRASPVEL_H
