// Generated by gencpp from file wam_common/BHandFingerVel.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_BHANDFINGERVEL_H
#define WAM_COMMON_MESSAGE_BHANDFINGERVEL_H

#include <ros/service_traits.h>


#include <wam_common/BHandFingerVelRequest.h>
#include <wam_common/BHandFingerVelResponse.h>


namespace wam_common
{

struct BHandFingerVel
{

typedef BHandFingerVelRequest Request;
typedef BHandFingerVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerVel
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::BHandFingerVel > {
  static const char* value()
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const ::wam_common::BHandFingerVel&) { return value(); }
};

template<>
struct DataType< ::wam_common::BHandFingerVel > {
  static const char* value()
  {
    return "wam_common/BHandFingerVel";
  }

  static const char* value(const ::wam_common::BHandFingerVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::BHandFingerVelRequest> should match
// service_traits::MD5Sum< ::wam_common::BHandFingerVel >
template<>
struct MD5Sum< ::wam_common::BHandFingerVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_common::BHandFingerVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandFingerVelRequest> should match
// service_traits::DataType< ::wam_common::BHandFingerVel >
template<>
struct DataType< ::wam_common::BHandFingerVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_common::BHandFingerVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::BHandFingerVelResponse> should match
// service_traits::MD5Sum< ::wam_common::BHandFingerVel >
template<>
struct MD5Sum< ::wam_common::BHandFingerVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_common::BHandFingerVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandFingerVelResponse> should match
// service_traits::DataType< ::wam_common::BHandFingerVel >
template<>
struct DataType< ::wam_common::BHandFingerVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_common::BHandFingerVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_BHANDFINGERVEL_H
