// Generated by gencpp from file wam_common/BHandFingerPos.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_BHANDFINGERPOS_H
#define WAM_COMMON_MESSAGE_BHANDFINGERPOS_H

#include <ros/service_traits.h>


#include <wam_common/BHandFingerPosRequest.h>
#include <wam_common/BHandFingerPosResponse.h>


namespace wam_common
{

struct BHandFingerPos
{

typedef BHandFingerPosRequest Request;
typedef BHandFingerPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerPos
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::BHandFingerPos > {
  static const char* value()
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const ::wam_common::BHandFingerPos&) { return value(); }
};

template<>
struct DataType< ::wam_common::BHandFingerPos > {
  static const char* value()
  {
    return "wam_common/BHandFingerPos";
  }

  static const char* value(const ::wam_common::BHandFingerPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::BHandFingerPosRequest> should match
// service_traits::MD5Sum< ::wam_common::BHandFingerPos >
template<>
struct MD5Sum< ::wam_common::BHandFingerPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_common::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandFingerPosRequest> should match
// service_traits::DataType< ::wam_common::BHandFingerPos >
template<>
struct DataType< ::wam_common::BHandFingerPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_common::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::BHandFingerPosResponse> should match
// service_traits::MD5Sum< ::wam_common::BHandFingerPos >
template<>
struct MD5Sum< ::wam_common::BHandFingerPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_common::BHandFingerPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::BHandFingerPosResponse> should match
// service_traits::DataType< ::wam_common::BHandFingerPos >
template<>
struct DataType< ::wam_common::BHandFingerPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_common::BHandFingerPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_BHANDFINGERPOS_H
