// Generated by gencpp from file wam_common/CartPosMove.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_CARTPOSMOVE_H
#define WAM_COMMON_MESSAGE_CARTPOSMOVE_H

#include <ros/service_traits.h>


#include <wam_common/CartPosMoveRequest.h>
#include <wam_common/CartPosMoveResponse.h>


namespace wam_common
{

struct CartPosMove
{

typedef CartPosMoveRequest Request;
typedef CartPosMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartPosMove
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::CartPosMove > {
  static const char* value()
  {
    return "993d3a0cca92114d34b338aeb1007ee4";
  }

  static const char* value(const ::wam_common::CartPosMove&) { return value(); }
};

template<>
struct DataType< ::wam_common::CartPosMove > {
  static const char* value()
  {
    return "wam_common/CartPosMove";
  }

  static const char* value(const ::wam_common::CartPosMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::CartPosMoveRequest> should match
// service_traits::MD5Sum< ::wam_common::CartPosMove >
template<>
struct MD5Sum< ::wam_common::CartPosMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::CartPosMove >::value();
  }
  static const char* value(const ::wam_common::CartPosMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::CartPosMoveRequest> should match
// service_traits::DataType< ::wam_common::CartPosMove >
template<>
struct DataType< ::wam_common::CartPosMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::CartPosMove >::value();
  }
  static const char* value(const ::wam_common::CartPosMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::CartPosMoveResponse> should match
// service_traits::MD5Sum< ::wam_common::CartPosMove >
template<>
struct MD5Sum< ::wam_common::CartPosMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::CartPosMove >::value();
  }
  static const char* value(const ::wam_common::CartPosMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::CartPosMoveResponse> should match
// service_traits::DataType< ::wam_common::CartPosMove >
template<>
struct DataType< ::wam_common::CartPosMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::CartPosMove >::value();
  }
  static const char* value(const ::wam_common::CartPosMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_CARTPOSMOVE_H
