// Generated by gencpp from file wam_common/ChangeMinirobotRequest.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_CHANGEMINIROBOTREQUEST_H
#define WAM_COMMON_MESSAGE_CHANGEMINIROBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct ChangeMinirobotRequest_
{
  typedef ChangeMinirobotRequest_<ContainerAllocator> Type;

  ChangeMinirobotRequest_()
    : minirobot(0.0)  {
    }
  ChangeMinirobotRequest_(const ContainerAllocator& _alloc)
    : minirobot(0.0)  {
  (void)_alloc;
    }



   typedef float _minirobot_type;
  _minirobot_type minirobot;





  typedef boost::shared_ptr< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeMinirobotRequest_

typedef ::wam_common::ChangeMinirobotRequest_<std::allocator<void> > ChangeMinirobotRequest;

typedef boost::shared_ptr< ::wam_common::ChangeMinirobotRequest > ChangeMinirobotRequestPtr;
typedef boost::shared_ptr< ::wam_common::ChangeMinirobotRequest const> ChangeMinirobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator1> & lhs, const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.minirobot == rhs.minirobot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator1> & lhs, const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12187c372a43953834c4cf2a3dd9d6e2";
  }

  static const char* value(const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12187c372a439538ULL;
  static const uint64_t static_value2 = 0x34c4cf2a3dd9d6e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/ChangeMinirobotRequest";
  }

  static const char* value(const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 minirobot\n"
;
  }

  static const char* value(const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.minirobot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeMinirobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::ChangeMinirobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::ChangeMinirobotRequest_<ContainerAllocator>& v)
  {
    s << indent << "minirobot: ";
    Printer<float>::stream(s, indent + "  ", v.minirobot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_CHANGEMINIROBOTREQUEST_H
