// Generated by gencpp from file wam_common/ChangeMinirobot.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_CHANGEMINIROBOT_H
#define WAM_COMMON_MESSAGE_CHANGEMINIROBOT_H

#include <ros/service_traits.h>


#include <wam_common/ChangeMinirobotRequest.h>
#include <wam_common/ChangeMinirobotResponse.h>


namespace wam_common
{

struct ChangeMinirobot
{

typedef ChangeMinirobotRequest Request;
typedef ChangeMinirobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeMinirobot
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::ChangeMinirobot > {
  static const char* value()
  {
    return "12187c372a43953834c4cf2a3dd9d6e2";
  }

  static const char* value(const ::wam_common::ChangeMinirobot&) { return value(); }
};

template<>
struct DataType< ::wam_common::ChangeMinirobot > {
  static const char* value()
  {
    return "wam_common/ChangeMinirobot";
  }

  static const char* value(const ::wam_common::ChangeMinirobot&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::ChangeMinirobotRequest> should match
// service_traits::MD5Sum< ::wam_common::ChangeMinirobot >
template<>
struct MD5Sum< ::wam_common::ChangeMinirobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::ChangeMinirobot >::value();
  }
  static const char* value(const ::wam_common::ChangeMinirobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::ChangeMinirobotRequest> should match
// service_traits::DataType< ::wam_common::ChangeMinirobot >
template<>
struct DataType< ::wam_common::ChangeMinirobotRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::ChangeMinirobot >::value();
  }
  static const char* value(const ::wam_common::ChangeMinirobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::ChangeMinirobotResponse> should match
// service_traits::MD5Sum< ::wam_common::ChangeMinirobot >
template<>
struct MD5Sum< ::wam_common::ChangeMinirobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::ChangeMinirobot >::value();
  }
  static const char* value(const ::wam_common::ChangeMinirobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::ChangeMinirobotResponse> should match
// service_traits::DataType< ::wam_common::ChangeMinirobot >
template<>
struct DataType< ::wam_common::ChangeMinirobotResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::ChangeMinirobot >::value();
  }
  static const char* value(const ::wam_common::ChangeMinirobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_CHANGEMINIROBOT_H
