// Generated by gencpp from file wam_common/DirMoveRequest.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_DIRMOVEREQUEST_H
#define WAM_COMMON_MESSAGE_DIRMOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct DirMoveRequest_
{
  typedef DirMoveRequest_<ContainerAllocator> Type;

  DirMoveRequest_()
    : direc()  {
    }
  DirMoveRequest_(const ContainerAllocator& _alloc)
    : direc(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direc_type;
  _direc_type direc;





  typedef boost::shared_ptr< ::wam_common::DirMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::DirMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DirMoveRequest_

typedef ::wam_common::DirMoveRequest_<std::allocator<void> > DirMoveRequest;

typedef boost::shared_ptr< ::wam_common::DirMoveRequest > DirMoveRequestPtr;
typedef boost::shared_ptr< ::wam_common::DirMoveRequest const> DirMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::DirMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::DirMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::DirMoveRequest_<ContainerAllocator1> & lhs, const ::wam_common::DirMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direc == rhs.direc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::DirMoveRequest_<ContainerAllocator1> & lhs, const ::wam_common::DirMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::DirMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::DirMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::DirMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::DirMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::DirMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::DirMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::DirMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74d315c33b71098916cb1e21a2e6a66f";
  }

  static const char* value(const ::wam_common::DirMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74d315c33b710989ULL;
  static const uint64_t static_value2 = 0x16cb1e21a2e6a66fULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::DirMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/DirMoveRequest";
  }

  static const char* value(const ::wam_common::DirMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::DirMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direc\n"
;
  }

  static const char* value(const ::wam_common::DirMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::DirMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DirMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::DirMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::DirMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "direc: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_DIRMOVEREQUEST_H
