// Generated by gencpp from file wam_common/GravityComp.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_GRAVITYCOMP_H
#define WAM_COMMON_MESSAGE_GRAVITYCOMP_H

#include <ros/service_traits.h>


#include <wam_common/GravityCompRequest.h>
#include <wam_common/GravityCompResponse.h>


namespace wam_common
{

struct GravityComp
{

typedef GravityCompRequest Request;
typedef GravityCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GravityComp
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::GravityComp > {
  static const char* value()
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const ::wam_common::GravityComp&) { return value(); }
};

template<>
struct DataType< ::wam_common::GravityComp > {
  static const char* value()
  {
    return "wam_common/GravityComp";
  }

  static const char* value(const ::wam_common::GravityComp&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::GravityCompRequest> should match
// service_traits::MD5Sum< ::wam_common::GravityComp >
template<>
struct MD5Sum< ::wam_common::GravityCompRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::GravityComp >::value();
  }
  static const char* value(const ::wam_common::GravityCompRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::GravityCompRequest> should match
// service_traits::DataType< ::wam_common::GravityComp >
template<>
struct DataType< ::wam_common::GravityCompRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::GravityComp >::value();
  }
  static const char* value(const ::wam_common::GravityCompRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::GravityCompResponse> should match
// service_traits::MD5Sum< ::wam_common::GravityComp >
template<>
struct MD5Sum< ::wam_common::GravityCompResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::GravityComp >::value();
  }
  static const char* value(const ::wam_common::GravityCompResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::GravityCompResponse> should match
// service_traits::DataType< ::wam_common::GravityComp >
template<>
struct DataType< ::wam_common::GravityCompResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::GravityComp >::value();
  }
  static const char* value(const ::wam_common::GravityCompResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_GRAVITYCOMP_H
