// Generated by gencpp from file wam_common/IdleWamRequest.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_IDLEWAMREQUEST_H
#define WAM_COMMON_MESSAGE_IDLEWAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct IdleWamRequest_
{
  typedef IdleWamRequest_<ContainerAllocator> Type;

  IdleWamRequest_()
    : colocated(false)  {
    }
  IdleWamRequest_(const ContainerAllocator& _alloc)
    : colocated(false)  {
  (void)_alloc;
    }



   typedef uint8_t _colocated_type;
  _colocated_type colocated;





  typedef boost::shared_ptr< ::wam_common::IdleWamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::IdleWamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IdleWamRequest_

typedef ::wam_common::IdleWamRequest_<std::allocator<void> > IdleWamRequest;

typedef boost::shared_ptr< ::wam_common::IdleWamRequest > IdleWamRequestPtr;
typedef boost::shared_ptr< ::wam_common::IdleWamRequest const> IdleWamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::IdleWamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::IdleWamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::IdleWamRequest_<ContainerAllocator1> & lhs, const ::wam_common::IdleWamRequest_<ContainerAllocator2> & rhs)
{
  return lhs.colocated == rhs.colocated;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::IdleWamRequest_<ContainerAllocator1> & lhs, const ::wam_common::IdleWamRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::IdleWamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::IdleWamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::IdleWamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::IdleWamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::IdleWamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::IdleWamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::IdleWamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5b49ecafd180af8ba5b1be89bbf053c";
  }

  static const char* value(const ::wam_common::IdleWamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5b49ecafd180af8ULL;
  static const uint64_t static_value2 = 0xba5b1be89bbf053cULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::IdleWamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/IdleWamRequest";
  }

  static const char* value(const ::wam_common::IdleWamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::IdleWamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool colocated\n"
;
  }

  static const char* value(const ::wam_common::IdleWamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::IdleWamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.colocated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdleWamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::IdleWamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::IdleWamRequest_<ContainerAllocator>& v)
  {
    s << indent << "colocated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.colocated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_IDLEWAMREQUEST_H
