// Generated by gencpp from file wam_common/OrtnMoveRequest.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_ORTNMOVEREQUEST_H
#define WAM_COMMON_MESSAGE_ORTNMOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct OrtnMoveRequest_
{
  typedef OrtnMoveRequest_<ContainerAllocator> Type;

  OrtnMoveRequest_()
    : orientation()  {
      orientation.assign(0.0);
  }
  OrtnMoveRequest_(const ContainerAllocator& _alloc)
    : orientation()  {
  (void)_alloc;
      orientation.assign(0.0);
  }



   typedef boost::array<float, 4>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::wam_common::OrtnMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::OrtnMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OrtnMoveRequest_

typedef ::wam_common::OrtnMoveRequest_<std::allocator<void> > OrtnMoveRequest;

typedef boost::shared_ptr< ::wam_common::OrtnMoveRequest > OrtnMoveRequestPtr;
typedef boost::shared_ptr< ::wam_common::OrtnMoveRequest const> OrtnMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::OrtnMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::OrtnMoveRequest_<ContainerAllocator1> & lhs, const ::wam_common::OrtnMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::OrtnMoveRequest_<ContainerAllocator1> & lhs, const ::wam_common::OrtnMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::OrtnMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::OrtnMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::OrtnMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const ::wam_common::OrtnMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86f723fe9a4be897ULL;
  static const uint64_t static_value2 = 0x9be87cd065276584ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/OrtnMoveRequest";
  }

  static const char* value(const ::wam_common::OrtnMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] orientation\n"
;
  }

  static const char* value(const ::wam_common::OrtnMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrtnMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::OrtnMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::OrtnMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_ORTNMOVEREQUEST_H
