// Generated by gencpp from file wam_common/Pose.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_POSE_H
#define WAM_COMMON_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <wam_common/PoseRequest.h>
#include <wam_common/PoseResponse.h>


namespace wam_common
{

struct Pose
{

typedef PoseRequest Request;
typedef PoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pose
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::Pose > {
  static const char* value()
  {
    return "0fb4bd8f0641709cff212b64f37d0e86";
  }

  static const char* value(const ::wam_common::Pose&) { return value(); }
};

template<>
struct DataType< ::wam_common::Pose > {
  static const char* value()
  {
    return "wam_common/Pose";
  }

  static const char* value(const ::wam_common::Pose&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::PoseRequest> should match
// service_traits::MD5Sum< ::wam_common::Pose >
template<>
struct MD5Sum< ::wam_common::PoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::Pose >::value();
  }
  static const char* value(const ::wam_common::PoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::PoseRequest> should match
// service_traits::DataType< ::wam_common::Pose >
template<>
struct DataType< ::wam_common::PoseRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::Pose >::value();
  }
  static const char* value(const ::wam_common::PoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::PoseResponse> should match
// service_traits::MD5Sum< ::wam_common::Pose >
template<>
struct MD5Sum< ::wam_common::PoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::Pose >::value();
  }
  static const char* value(const ::wam_common::PoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::PoseResponse> should match
// service_traits::DataType< ::wam_common::Pose >
template<>
struct DataType< ::wam_common::PoseResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::Pose >::value();
  }
  static const char* value(const ::wam_common::PoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_POSE_H
