// Generated by gencpp from file wam_common/PoseMove.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_POSEMOVE_H
#define WAM_COMMON_MESSAGE_POSEMOVE_H

#include <ros/service_traits.h>


#include <wam_common/PoseMoveRequest.h>
#include <wam_common/PoseMoveResponse.h>


namespace wam_common
{

struct PoseMove
{

typedef PoseMoveRequest Request;
typedef PoseMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseMove
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::PoseMove > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::wam_common::PoseMove&) { return value(); }
};

template<>
struct DataType< ::wam_common::PoseMove > {
  static const char* value()
  {
    return "wam_common/PoseMove";
  }

  static const char* value(const ::wam_common::PoseMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::PoseMoveRequest> should match
// service_traits::MD5Sum< ::wam_common::PoseMove >
template<>
struct MD5Sum< ::wam_common::PoseMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::PoseMove >::value();
  }
  static const char* value(const ::wam_common::PoseMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::PoseMoveRequest> should match
// service_traits::DataType< ::wam_common::PoseMove >
template<>
struct DataType< ::wam_common::PoseMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::PoseMove >::value();
  }
  static const char* value(const ::wam_common::PoseMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::PoseMoveResponse> should match
// service_traits::MD5Sum< ::wam_common::PoseMove >
template<>
struct MD5Sum< ::wam_common::PoseMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::PoseMove >::value();
  }
  static const char* value(const ::wam_common::PoseMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::PoseMoveResponse> should match
// service_traits::DataType< ::wam_common::PoseMove >
template<>
struct DataType< ::wam_common::PoseMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::PoseMove >::value();
  }
  static const char* value(const ::wam_common::PoseMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_POSEMOVE_H
