// Generated by gencpp from file wam_common/RTJointTrq.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_RTJOINTTRQ_H
#define WAM_COMMON_MESSAGE_RTJOINTTRQ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct RTJointTrq_
{
  typedef RTJointTrq_<ContainerAllocator> Type;

  RTJointTrq_()
    : torques()  {
    }
  RTJointTrq_(const ContainerAllocator& _alloc)
    : torques(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _torques_type;
  _torques_type torques;





  typedef boost::shared_ptr< ::wam_common::RTJointTrq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::RTJointTrq_<ContainerAllocator> const> ConstPtr;

}; // struct RTJointTrq_

typedef ::wam_common::RTJointTrq_<std::allocator<void> > RTJointTrq;

typedef boost::shared_ptr< ::wam_common::RTJointTrq > RTJointTrqPtr;
typedef boost::shared_ptr< ::wam_common::RTJointTrq const> RTJointTrqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::RTJointTrq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::RTJointTrq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::RTJointTrq_<ContainerAllocator1> & lhs, const ::wam_common::RTJointTrq_<ContainerAllocator2> & rhs)
{
  return lhs.torques == rhs.torques;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::RTJointTrq_<ContainerAllocator1> & lhs, const ::wam_common::RTJointTrq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::RTJointTrq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::RTJointTrq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::RTJointTrq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::RTJointTrq_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::RTJointTrq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::RTJointTrq_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::RTJointTrq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eee8a087b75bc454bfb2231a0ca7e0f2";
  }

  static const char* value(const ::wam_common::RTJointTrq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeee8a087b75bc454ULL;
  static const uint64_t static_value2 = 0xbfb2231a0ca7e0f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::RTJointTrq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/RTJointTrq";
  }

  static const char* value(const ::wam_common::RTJointTrq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::RTJointTrq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] torques\n"
;
  }

  static const char* value(const ::wam_common::RTJointTrq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::RTJointTrq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torques);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTJointTrq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::RTJointTrq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::RTJointTrq_<ContainerAllocator>& v)
  {
    s << indent << "torques[]" << std::endl;
    for (size_t i = 0; i < v.torques.size(); ++i)
    {
      s << indent << "  torques[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.torques[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_RTJOINTTRQ_H
