// Generated by gencpp from file wam_common/RTOrtnPos.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_RTORTNPOS_H
#define WAM_COMMON_MESSAGE_RTORTNPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_common
{
template <class ContainerAllocator>
struct RTOrtnPos_
{
  typedef RTOrtnPos_<ContainerAllocator> Type;

  RTOrtnPos_()
    : orientation()
    , rate_limits()  {
      orientation.assign(0.0);

      rate_limits.assign(0.0);
  }
  RTOrtnPos_(const ContainerAllocator& _alloc)
    : orientation()
    , rate_limits()  {
  (void)_alloc;
      orientation.assign(0.0);

      rate_limits.assign(0.0);
  }



   typedef boost::array<float, 4>  _orientation_type;
  _orientation_type orientation;

   typedef boost::array<float, 4>  _rate_limits_type;
  _rate_limits_type rate_limits;





  typedef boost::shared_ptr< ::wam_common::RTOrtnPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_common::RTOrtnPos_<ContainerAllocator> const> ConstPtr;

}; // struct RTOrtnPos_

typedef ::wam_common::RTOrtnPos_<std::allocator<void> > RTOrtnPos;

typedef boost::shared_ptr< ::wam_common::RTOrtnPos > RTOrtnPosPtr;
typedef boost::shared_ptr< ::wam_common::RTOrtnPos const> RTOrtnPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_common::RTOrtnPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_common::RTOrtnPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wam_common::RTOrtnPos_<ContainerAllocator1> & lhs, const ::wam_common::RTOrtnPos_<ContainerAllocator2> & rhs)
{
  return lhs.orientation == rhs.orientation &&
    lhs.rate_limits == rhs.rate_limits;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wam_common::RTOrtnPos_<ContainerAllocator1> & lhs, const ::wam_common::RTOrtnPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wam_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wam_common::RTOrtnPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_common::RTOrtnPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::RTOrtnPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_common::RTOrtnPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::RTOrtnPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_common::RTOrtnPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_common::RTOrtnPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b352081db430205c87e0e439f09a0b2";
  }

  static const char* value(const ::wam_common::RTOrtnPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b352081db430205ULL;
  static const uint64_t static_value2 = 0xc87e0e439f09a0b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_common::RTOrtnPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_common/RTOrtnPos";
  }

  static const char* value(const ::wam_common::RTOrtnPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_common::RTOrtnPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] orientation\n"
"float32[4] rate_limits\n"
;
  }

  static const char* value(const ::wam_common::RTOrtnPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_common::RTOrtnPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
      stream.next(m.rate_limits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTOrtnPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_common::RTOrtnPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_common::RTOrtnPos_<ContainerAllocator>& v)
  {
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "rate_limits[]" << std::endl;
    for (size_t i = 0; i < v.rate_limits.size(); ++i)
    {
      s << indent << "  rate_limits[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rate_limits[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_COMMON_MESSAGE_RTORTNPOS_H
