// Generated by gencpp from file wam_common/WristRotate.msg
// DO NOT EDIT!


#ifndef WAM_COMMON_MESSAGE_WRISTROTATE_H
#define WAM_COMMON_MESSAGE_WRISTROTATE_H

#include <ros/service_traits.h>


#include <wam_common/WristRotateRequest.h>
#include <wam_common/WristRotateResponse.h>


namespace wam_common
{

struct WristRotate
{

typedef WristRotateRequest Request;
typedef WristRotateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WristRotate
} // namespace wam_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_common::WristRotate > {
  static const char* value()
  {
    return "6e0612db1e37d19bf6d235a2f7aa4964";
  }

  static const char* value(const ::wam_common::WristRotate&) { return value(); }
};

template<>
struct DataType< ::wam_common::WristRotate > {
  static const char* value()
  {
    return "wam_common/WristRotate";
  }

  static const char* value(const ::wam_common::WristRotate&) { return value(); }
};


// service_traits::MD5Sum< ::wam_common::WristRotateRequest> should match
// service_traits::MD5Sum< ::wam_common::WristRotate >
template<>
struct MD5Sum< ::wam_common::WristRotateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::WristRotate >::value();
  }
  static const char* value(const ::wam_common::WristRotateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::WristRotateRequest> should match
// service_traits::DataType< ::wam_common::WristRotate >
template<>
struct DataType< ::wam_common::WristRotateRequest>
{
  static const char* value()
  {
    return DataType< ::wam_common::WristRotate >::value();
  }
  static const char* value(const ::wam_common::WristRotateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_common::WristRotateResponse> should match
// service_traits::MD5Sum< ::wam_common::WristRotate >
template<>
struct MD5Sum< ::wam_common::WristRotateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_common::WristRotate >::value();
  }
  static const char* value(const ::wam_common::WristRotateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_common::WristRotateResponse> should match
// service_traits::DataType< ::wam_common::WristRotate >
template<>
struct DataType< ::wam_common::WristRotateResponse>
{
  static const char* value()
  {
    return DataType< ::wam_common::WristRotate >::value();
  }
  static const char* value(const ::wam_common::WristRotateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_COMMON_MESSAGE_WRISTROTATE_H
