
classdef BHandGraspVelRequest < ros.Message
    %BHandGraspVelRequest MATLAB implementation of wam_common/BHandGraspVelRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/BHandGraspVelRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e4ff88b32504f688719a85e0753f63ce' % The MD5 Checksum of the message definition
        PropertyList = { 'Velocity' } % List of non-constant message properties
        ROSPropertyList = { 'velocity' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Velocity
    end
    methods
        function set.Velocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'BHandGraspVelRequest', 'Velocity');
            obj.Velocity = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.BHandGraspVelRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.BHandGraspVelRequest(strObj);
        end
    end
end
