
classdef CartPosMoveRequest < ros.Message
    %CartPosMoveRequest MATLAB implementation of wam_common/CartPosMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/CartPosMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '993d3a0cca92114d34b338aeb1007ee4' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' } % List of non-constant message properties
        ROSPropertyList = { 'position' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
    end
    methods
        function set.Position(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'CartPosMoveRequest', 'Position');
            obj.Position = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.CartPosMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.CartPosMoveRequest(strObj);
        end
    end
end
