
classdef ChangeMinirobotRequest < ros.Message
    %ChangeMinirobotRequest MATLAB implementation of wam_common/ChangeMinirobotRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/ChangeMinirobotRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '12187c372a43953834c4cf2a3dd9d6e2' % The MD5 Checksum of the message definition
        PropertyList = { 'Minirobot' } % List of non-constant message properties
        ROSPropertyList = { 'minirobot' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Minirobot
    end
    methods
        function set.Minirobot(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ChangeMinirobotRequest', 'Minirobot');
            obj.Minirobot = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.ChangeMinirobotRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.ChangeMinirobotRequest(strObj);
        end
    end
end
