
classdef DirMoveRequest < ros.Message
    %DirMoveRequest MATLAB implementation of wam_common/DirMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/DirMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '74d315c33b71098916cb1e21a2e6a66f' % The MD5 Checksum of the message definition
        PropertyList = { 'Direc' } % List of non-constant message properties
        ROSPropertyList = { 'direc' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Direc
    end
    methods
        function set.Direc(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'DirMoveRequest', 'Direc');
            obj.Direc = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.DirMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.DirMoveRequest(strObj);
        end
    end
end
