
classdef GravityCompRequest < ros.Message
    %GravityCompRequest MATLAB implementation of wam_common/GravityCompRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/GravityCompRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f83a9fe078fab9865d863fbf215e1c14' % The MD5 Checksum of the message definition
        PropertyList = { 'Gravity' } % List of non-constant message properties
        ROSPropertyList = { 'gravity' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Gravity
    end
    methods
        function set.Gravity(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GravityCompRequest', 'Gravity');
            obj.Gravity = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.GravityCompRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.GravityCompRequest(strObj);
        end
    end
end
