
classdef IdleWamRequest < ros.Message
    %IdleWamRequest MATLAB implementation of wam_common/IdleWamRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/IdleWamRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b5b49ecafd180af8ba5b1be89bbf053c' % The MD5 Checksum of the message definition
        PropertyList = { 'Colocated' } % List of non-constant message properties
        ROSPropertyList = { 'colocated' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Colocated
    end
    methods
        function set.Colocated(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'IdleWamRequest', 'Colocated');
            obj.Colocated = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.IdleWamRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.IdleWamRequest(strObj);
        end
    end
end
