
classdef MoveRequest < ros.Message
    %MoveRequest MATLAB implementation of wam_common/MoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/MoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1ce238898166ce57c9f3f359833b9d6e' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' 'Orientation' } % List of non-constant message properties
        ROSPropertyList = { 'position' 'orientation' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Point' ...
            'ros.msggen.std_msgs.Float32MultiArray' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
        Orientation
    end
    methods
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'MoveRequest', 'Position')
            obj.Position = val;
        end
        function set.Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Float32MultiArray'};
            validateattributes(val, validClasses, validAttributes, 'MoveRequest', 'Orientation')
            obj.Orientation = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.MoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.MoveRequest(strObj);
        end
    end
end
