
classdef PoseResponse < ros.Message
    %PoseResponse MATLAB implementation of wam_common/PoseResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/PoseResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '0fb4bd8f0641709cff212b64f37d0e86' % The MD5 Checksum of the message definition
        PropertyList = { 'Pose' 'OrientMatrix' } % List of non-constant message properties
        ROSPropertyList = { 'pose' 'orientMatrix' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
            'ros.msggen.std_msgs.Float32MultiArray' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pose
        OrientMatrix
    end
    methods
        function set.Pose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'PoseResponse', 'Pose')
            obj.Pose = val;
        end
        function set.OrientMatrix(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Float32MultiArray'};
            validateattributes(val, validClasses, validAttributes, 'PoseResponse', 'OrientMatrix')
            obj.OrientMatrix = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.PoseResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.PoseResponse(strObj);
        end
    end
end
