
classdef RTCartPos < ros.Message
    %RTCartPos MATLAB implementation of wam_common/RTCartPos
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/RTCartPos' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f40423d4ca09896785d982c621cba554' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' 'RateLimits' } % List of non-constant message properties
        ROSPropertyList = { 'position' 'rate_limits' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
        RateLimits
    end
    methods
        function set.Position(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'RTCartPos', 'Position');
            obj.Position = single(val);
        end
        function set.RateLimits(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'RTCartPos', 'RateLimits');
            obj.RateLimits = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.RTCartPos.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.RTCartPos(strObj);
        end
    end
end
