
classdef RTJointPos < ros.Message
    %RTJointPos MATLAB implementation of wam_common/RTJointPos
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/RTJointPos' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6db71b8c4d3c870c701b3f89e85b7a36' % The MD5 Checksum of the message definition
        PropertyList = { 'Joints' 'RateLimits' } % List of non-constant message properties
        ROSPropertyList = { 'joints' 'rate_limits' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Joints
        RateLimits
    end
    methods
        function set.Joints(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RTJointPos', 'Joints');
            obj.Joints = single(val);
        end
        function set.RateLimits(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RTJointPos', 'RateLimits');
            obj.RateLimits = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.RTJointPos.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.RTJointPos(strObj);
        end
    end
end
