
classdef RTJointVel < ros.Message
    %RTJointVel MATLAB implementation of wam_common/RTJointVel
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/RTJointVel' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '9b1dee67c9ae4d5adf87be09d4bf02ef' % The MD5 Checksum of the message definition
        PropertyList = { 'Velocities' } % List of non-constant message properties
        ROSPropertyList = { 'velocities' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Velocities
    end
    methods
        function set.Velocities(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RTJointVel', 'Velocities');
            obj.Velocities = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.RTJointVel.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.RTJointVel(strObj);
        end
    end
end
