
classdef RTOrtnPos < ros.Message
    %RTOrtnPos MATLAB implementation of wam_common/RTOrtnPos
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/RTOrtnPos' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5b352081db430205c87e0e439f09a0b2' % The MD5 Checksum of the message definition
        PropertyList = { 'Orientation' 'RateLimits' } % List of non-constant message properties
        ROSPropertyList = { 'orientation' 'rate_limits' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Orientation
        RateLimits
    end
    methods
        function set.Orientation(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 4};
            validateattributes(val, validClasses, validAttributes, 'RTOrtnPos', 'Orientation');
            obj.Orientation = single(val);
        end
        function set.RateLimits(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 4};
            validateattributes(val, validClasses, validAttributes, 'RTOrtnPos', 'RateLimits');
            obj.RateLimits = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.RTOrtnPos.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.RTOrtnPos(strObj);
        end
    end
end
