
classdef RTOrtnVel < ros.Message
    %RTOrtnVel MATLAB implementation of wam_common/RTOrtnVel
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/RTOrtnVel' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2326f85574083a0a1fc4fddeff59781c' % The MD5 Checksum of the message definition
        PropertyList = { 'Angular' 'Magnitude' } % List of non-constant message properties
        ROSPropertyList = { 'angular' 'magnitude' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Angular
        Magnitude
    end
    methods
        function set.Angular(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'RTOrtnVel', 'Angular');
            obj.Angular = single(val);
        end
        function set.Magnitude(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RTOrtnVel', 'Magnitude');
            obj.Magnitude = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.RTOrtnVel.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.RTOrtnVel(strObj);
        end
    end
end
