
classdef WristResponse < ros.Message
    %WristResponse MATLAB implementation of wam_common/WristResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/WristResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f86fdbd3e330ea48b43168fdd8a60964' % The MD5 Checksum of the message definition
        PropertyList = { 'Jp' } % List of non-constant message properties
        ROSPropertyList = { 'jp' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Jp
    end
    methods
        function set.Jp(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'WristResponse', 'Jp');
            obj.Jp = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.WristResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.WristResponse(strObj);
        end
    end
end
