
classdef Location < ros.Message
    %Location MATLAB implementation of wam_msgs/Location
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_msgs/Location' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6b442292d4660bd1e8b790fcc52b116b' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Columna1Orientation' 'Columna2Orientation' 'Columna3Orientation' 'Columna4Position' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'columna1_orientation' 'columna2_orientation' 'columna3_orientation' 'columna4_position' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Point' ...
            'ros.msggen.geometry_msgs.Point' ...
            'ros.msggen.geometry_msgs.Point' ...
            'ros.msggen.geometry_msgs.Point' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Columna1Orientation
        Columna2Orientation
        Columna3Orientation
        Columna4Position
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'Location', 'Header')
            obj.Header = val;
        end
        function set.Columna1Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'Location', 'Columna1Orientation')
            obj.Columna1Orientation = val;
        end
        function set.Columna2Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'Location', 'Columna2Orientation')
            obj.Columna2Orientation = val;
        end
        function set.Columna3Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'Location', 'Columna3Orientation')
            obj.Columna3Orientation = val;
        end
        function set.Columna4Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'Location', 'Columna4Position')
            obj.Columna4Position = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_msgs.Location.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_msgs.Location(strObj);
        end
    end
end
