
classdef CouplingWamRequest < ros.Message
    %CouplingWamRequest MATLAB implementation of wam_common/CouplingWamRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/CouplingWamRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '673873b0d5bf0a07d3f41369f70ccd47' % The MD5 Checksum of the message definition
        PropertyList = { 'CouplingCamera' 'CouplingIlumination' } % List of non-constant message properties
        ROSPropertyList = { 'couplingCamera' 'couplingIlumination' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CouplingCamera
        CouplingIlumination
    end
    methods
        function set.CouplingCamera(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CouplingWamRequest', 'CouplingCamera');
            obj.CouplingCamera = logical(val);
        end
        function set.CouplingIlumination(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CouplingWamRequest', 'CouplingIlumination');
            obj.CouplingIlumination = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.CouplingWamRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.CouplingWamRequest(strObj);
        end
    end
end
