
classdef JointMoveRequest < ros.Message
    %JointMoveRequest MATLAB implementation of wam_common/JointMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/JointMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e2a0e438b445b98def0f0ba6a2a85f58' % The MD5 Checksum of the message definition
        PropertyList = { 'Joints' } % List of non-constant message properties
        ROSPropertyList = { 'joints' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Joints
    end
    methods
        function set.Joints(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointMoveRequest', 'Joints');
            obj.Joints = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.JointMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.JointMoveRequest(strObj);
        end
    end
end
