
classdef OrtnMoveRequest < ros.Message
    %OrtnMoveRequest MATLAB implementation of wam_common/OrtnMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/OrtnMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '86f723fe9a4be8979be87cd065276584' % The MD5 Checksum of the message definition
        PropertyList = { 'Orientation' } % List of non-constant message properties
        ROSPropertyList = { 'orientation' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Orientation
    end
    methods
        function set.Orientation(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 4};
            validateattributes(val, validClasses, validAttributes, 'OrtnMoveRequest', 'Orientation');
            obj.Orientation = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.OrtnMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.OrtnMoveRequest(strObj);
        end
    end
end
