
classdef PoseMoveRequest < ros.Message
    %PoseMoveRequest MATLAB implementation of wam_common/PoseMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/PoseMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f192399f711a48924df9a394d37edd67' % The MD5 Checksum of the message definition
        PropertyList = { 'Pose' } % List of non-constant message properties
        ROSPropertyList = { 'pose' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pose
    end
    methods
        function set.Pose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'PoseMoveRequest', 'Pose')
            obj.Pose = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.PoseMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.PoseMoveRequest(strObj);
        end
    end
end
