
classdef RTCartVel < ros.Message
    %RTCartVel MATLAB implementation of wam_common/RTCartVel
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'wam_common/RTCartVel' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'bde6e49ce1902bc915138d25af0e9ef1' % The MD5 Checksum of the message definition
        PropertyList = { 'Direction' 'Magnitude' } % List of non-constant message properties
        ROSPropertyList = { 'direction' 'magnitude' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Direction
        Magnitude
    end
    methods
        function set.Direction(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'RTCartVel', 'Direction');
            obj.Direction = single(val);
        end
        function set.Magnitude(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RTCartVel', 'Magnitude');
            obj.Magnitude = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.wam_common.RTCartVel.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.wam_common.RTCartVel(strObj);
        end
    end
end
